---
title: "Software enviroment"
---

This page describes how to install boolean network simulation tools and related software.

## Learn to use pixi

The best way to do scientific computing is via [pixi] environment management. With pixi you can create isolated software environments with a wide range of software packages. Pixi is the next generation of `conda` environment management. All instructions here assume that you have `pixi` installed.

[pixi]: https://pixi.prefix.dev/latest/installation/

## Initialize a project

In a new project directory run:

```bash
# Initialize a new project
pixi init
```

This creates the `pixi.toml` file which contains the project configuration. Now add software to the environment.

## Activate 

Load a shell with the environment activated (analogous to `conda activate my-environment`).

```bash
# Activate the enviroment
pixi shell
```

## Install software

Add software to the environment.

```bash
# Add Python 3.12 and some useful packages
pixi add python=3.12 pip click graphviz

# Install pyboolnet
pip install git+https://github.com/hklarner/pyboolnet@3.0.16
```

## TODO

cuda, and more advance software installation instructions go here

[clasp][clasp] is an answer set solver for (extended) normal and disjunctive logic programs.

```bash
# Install clingo
pixi add -c potassco:clingo
```

[clasp]: https://potassco.org/clasp/

